Layout:
  Metrics/LineLength:
    Max: 120

AllCops:
  Exclude:
    - 'rails*-example/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 11
