Layout:
  Metrics/LineLength:
    Max: 120

AllCops:
  Exclude:
    - 'rails-example/**/*'
    - 'rails6-example/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 11
